In [2]:
import numpy as np

In [3]:
np.arange(0,100,3) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [4]:
np.linspace(0,100,5) # 0 ile 100 arası değerleri 5 parçaya böler.

array([  0.,  25.,  50.,  75., 100.])

In [6]:
np.random.randint(1,10,5) # 1(dahil) ile 10(hariç) arasında 5 değer oluşturarak 5 değer saklayan array oluşturur.

array([7, 9, 2, 2, 4])

In [7]:
np.random.rand(5) # 0 ile 1 arasında 5 float değerler oluşturur.

array([0.78596475, 0.12027395, 0.2684878 , 0.15336838, 0.76276028])

In [8]:
np.random.randn(10) # 0 etrafında - ve + değerlerle Gaussian Distribution'a göre değerler oluşturur.

array([ 0.17665061, -1.20009957,  0.28817694, -3.51433602,  0.1191627 ,
       -1.79171413, -0.54921118, -0.09909486,  0.44843732,  0.40251028])

In [ ]:
arr.reshape(5,5) # 5 x 5 =  25 tek boyutlu matrisi 2 boyuta çevirir.
arr.max()
arr.min()
arr.sum() # Tüm değerlerin toplamı
arr.mean() # Ortalama Bulur 
arr.argmin() # En küçük eleman 6.indekste
arr.argmax() # En büyük eleman 7.indekste

In [ ]:
#Determinant hesaplama
detArray =  np.random.randint(1,100,25)
# array([ 5, 54, 55, 62, 83, 73, 52, 62,  8, 95, 64, 82, 27, 79, 58, 23,  9,
#        34, 25, 30, 40, 58, 97, 75, 36])
detArray = detArray.reshape(5,5)
# array([[ 5, 54, 55, 62, 83],
#        [73, 52, 62,  8, 95],
#        [64, 82, 27, 79, 58],
#        [23,  9, 34, 25, 30],
#        [40, 58, 97, 75, 36]])
np.linalg.det(detArray)
# -802623845.9999968
round(np.linalg.det(detArray))
# -802623846.0
detArray2 = np.array([[1,2],[3,4]])
round(np.linalg.det(detArray2))
# -2.0

In [ ]:
#OOP yapısı DİKKAT
arr2 = arr
arr2[:3] =  25 #yaparsak arr de değişmiş olacak. Çünkü ikisi de aynı yeri gösteriyor.Dolayısıyla arr.copy() yapmalıyız.